name: Run MissNoMail Daily

on:
  schedule:
    # Runs daily at 5:15 PM GMT+5:30 (11:45 AM UTC)
    - cron: "45 11 * * *"
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script-main:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      LLM_MODEL: ${{secrets.LLM_MODEL}}
      SENDER_GMAIL_ADDRESS: ${{ secrets.SENDER_GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{secrets.GMAIL_APP_PASSWORD}}
      RECEIVER_GMAIL_ADDRESS: ${{secrets.RECEIVER_GMAIL_ADDRESS}}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set-Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up token.json
        run: echo "${{ secrets.TOKEN_JSON }}" > token.json

      - name: Run Main
        run: python main.py
